(()=>{
  const SUPABASE_URL='https://nynssdxfmjfqgodgynnu.supabase.co',KEY='sb_publishable_ose18MeKd0ZPfTM1tbq2fg_hzfVcTxf';
  const sb=window.supabase.createClient(SUPABASE_URL,KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),root=document.querySelector('#doc'),money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});
  const token=new URLSearchParams(location.search).get('t');if(!token){fail('This invoice link is missing.');return}load();
  async function load(){try{const r=await sb.rpc('get_public_invoice',{share_token:token});if(r.error)throw r.error;render(r.data)}catch(e){fail(e?.message||'Could not load this invoice.')}}
  function render(i){
    const status=displayStatus(i),items=Array.isArray(i.items)?i.items:[],brand=document.querySelector('.doc-brand strong'),sub=document.querySelector('.doc-brand small');if(brand)brand.textContent=i.company_name||'TradeOS';if(sub)sub.textContent=i.trade_type||'Customer invoice';
    const business=[i.company_address,i.company_phone,i.company_email,i.company_website].filter(Boolean).map(esc).join('\n');
    const registrations=[i.company_number?`Company no. ${esc(i.company_number)}`:'',i.vat_number?`VAT no. ${esc(i.vat_number)}`:''].filter(Boolean).join(' · ');
    const hasBank=i.bank_account_name||i.bank_sort_code||i.bank_account_number;
    root.innerHTML=`<article class="doc-paper"><header class="doc-head"><p class="doc-kicker">INVOICE</p><h1>${esc(i.invoice_number||'Invoice')}</h1><div class="doc-head-sub"><span class="doc-ref">${i.job_title?`${esc(i.job_title)} · `:''}${date(i.created_at)}</span><span class="doc-status ${esc(status)}">${esc(status.replace('_',' '))}</span></div></header><div class="doc-body">
      <div class="doc-grid"><div class="doc-info"><span>From</span><strong>${esc(i.company_name||'Trade business')}${i.trade_type?`\n${esc(i.trade_type)}`:''}${business?`\n${business}`:''}</strong>${registrations?`<small class="doc-mini">${registrations}</small>`:''}</div><div class="doc-info"><span>Bill to</span><strong>${esc(i.customer_name||'Customer')}${i.customer_address?`\n${esc(i.customer_address)}`:''}</strong></div></div>
      <div class="doc-grid"><div class="doc-info"><span>Invoice date</span><strong>${date(i.created_at)}</strong></div><div class="doc-info"><span>Due date</span><strong>${i.due_date?dateOnly(i.due_date):'Not set'}</strong></div></div>
      <section class="doc-section"><h2>Invoice items</h2><div class="doc-breakdown">${items.length?items.map(x=>`<div class="doc-row"><span>${esc(x.description||'Work')}${Number(x.quantity||1)!==1?` × ${Number(x.quantity)}`:''}</span><strong>${money.format(Number(x.line_total||0))}</strong></div>`).join(''):`<div class="doc-row"><span>${esc(i.job_title||'Work')}</span><strong>${money.format(Number(i.subtotal||0)+Number(i.vat||0))}</strong></div>`}<div class="doc-row"><span>Net</span><strong>${money.format(Number(i.subtotal||0))}</strong></div><div class="doc-row"><span>VAT</span><strong>${money.format(Number(i.vat||0))}</strong></div><div class="doc-row total"><span>Total</span><strong>${money.format(Number(i.total||0))}</strong></div></div></section>
      <div class="doc-summary"><div class="doc-money"><span>Paid</span><strong>${money.format(Number(i.paid||0))}</strong></div><div class="doc-money due"><span>Balance due</span><strong>${money.format(Number(i.outstanding||0))}</strong></div></div>
      ${Number(i.outstanding||0)>0&&hasBank?`<section class="doc-section doc-bank"><h2>Pay by bank transfer</h2><div class="doc-bank-grid">${i.bank_account_name?`<div><span>Account name</span><strong>${esc(i.bank_account_name)}</strong></div>`:''}${i.bank_sort_code?`<div><span>Sort code</span><strong>${esc(i.bank_sort_code)}</strong></div>`:''}${i.bank_account_number?`<div><span>Account number</span><strong>${esc(i.bank_account_number)}</strong></div>`:''}<div><span>Reference</span><strong>${esc(i.invoice_number||'Invoice')}</strong></div></div></section>`:''}
      ${i.notes?`<section class="doc-section"><h2>Notes</h2><p class="doc-copy">${esc(i.notes)}</p></section>`:''}${i.invoice_terms?`<section class="doc-section doc-terms"><h2>Payment terms</h2><p class="doc-copy">${esc(i.invoice_terms)}</p></section>`:''}
      ${Number(i.outstanding||0)<=0?`<div class="doc-result"><strong>Paid in full</strong><p>Thank you — this invoice has been fully paid.</p></div>`:status==='overdue'?`<div class="doc-result expired"><strong>Payment overdue</strong><p>Please arrange payment of ${money.format(Number(i.outstanding||0))} or contact ${esc(i.company_name||'the trade business')} if you need to discuss this invoice.</p></div>`:''}
      <div class="doc-actions single"><button class="doc-btn primary" data-print>Print / Save PDF</button></div><p class="doc-note">Keep this secure link for your records. The payment status updates automatically when a payment is recorded.</p>
    </div></article>`;root.querySelector('[data-print]')?.addEventListener('click',()=>window.print());
  }
  function displayStatus(i){if(Number(i.outstanding||0)<=.005)return'paid';if(i.status==='void')return'void';if(i.due_date&&new Date(`${i.due_date}T23:59:59`).getTime()<Date.now())return'overdue';return String(i.status||'sent').toLowerCase()}
  function fail(m){root.innerHTML=`<div class="doc-error"><strong>Invoice unavailable</strong><div>${esc(m)}</div></div>`}
  function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(d)}
  function dateOnly(v){const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(d)}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();