(()=>{
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});
const fmt=new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'});
let data=null,view='home',companyId=null,week=monday(new Date());
const root=document.getElementById('root');
start();

async function req(api,body,method='POST'){
  const u=new URL(location.href);u.search='';u.searchParams.set('api',api);
  if(api==='bootstrap'){
    if(companyId)u.searchParams.set('companyId',companyId);
    u.searchParams.set('weekStart',week);
  }
  const o={method,credentials:'same-origin',headers:{accept:'application/json'}};
  if(body!==undefined){o.headers['content-type']='application/json';o.body=JSON.stringify(body)}
  const r=await fetch(u,o);const j=await r.json().catch(()=>({}));
  if(r.status===401)throw new Error('AUTH');
  if(!r.ok)throw new Error(j.error||'Request failed');
  return j;
}

async function start(){try{await refresh()}catch(e){auth(e.message==='AUTH'?'':e.message)}}
async function refresh(){data=await req('bootstrap',undefined,'GET');if(!companyId&&data.activeCompany)companyId=data.activeCompany.id;render()}

function auth(msg=''){
  root.innerHTML=`<div class="auth-shell"><section class="card auth-card"><p class="eyebrow">VEYSTEAD CLOUD BETA</p><h2>One live workspace for the whole team.</h2><p class="sub">Sign in to manage quotes, jobs, timesheets, profit, invoices and payments.</p><form id="auth"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="8" required></div><div class="auth-actions"><button class="btn">Sign in</button><button class="btn secondary" type="button" id="signup">Create account</button></div></form>${msg?`<div class="error">${esc(msg)}</div>`:''}<div id="authmsg"></div></section></div>`;
  const f=$('#auth');f.onsubmit=e=>{e.preventDefault();login('signin',f)};$('#signup').onclick=()=>login('signup',f)
}
async function login(action,f){const x=new FormData(f),m=$('#authmsg');m.innerHTML='';try{const r=await req(action,{email:x.get('email'),password:x.get('password')});if(r.session)await refresh();else m.innerHTML=`<div class="success">${esc(r.message||'Check your email, then sign in.')}</div>`}catch(e){m.innerHTML=`<div class="error">${esc(e.message==='AUTH'?'Sign in failed':e.message)}</div>`}}

function setup(){
  root.innerHTML=`<div class="auth-shell"><section class="card auth-card"><p class="eyebrow">VEYSTEAD SETUP</p><h2>Create your company workspace</h2><p class="sub">If you were invited with this email, Veystead will join you automatically. Otherwise create a workspace.</p><form id="setup"><div class="field"><label>Company name</label><input name="companyName" required></div><div class="field"><label>Your name</label><input name="ownerName" required></div><div class="field"><label>Trade</label><input name="tradeType" value="Electrician"></div><button class="btn">Create workspace</button><button class="btn secondary" type="button" id="logout">Sign out</button></form><div id="setupmsg"></div></section></div>`;
  $('#setup').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await req('create_company',Object.fromEntries(f.entries()));await refresh()}catch(err){$('#setupmsg').innerHTML=`<div class="error">${esc(err.message)}</div>`}};$('#logout').onclick=logout
}

function render(){
  if(!data?.user)return auth();if(!data.memberships?.length)return setup();
  const role=data.activeMembership.role,isManager=['owner','admin','manager'].includes(role);
  root.innerHTML=`<div class="app"><header class="topbar"><div class="brand"><div class="logo">T</div><h1>Veystead</h1></div><div class="toolbar">${data.memberships.length>1?`<select id="company">${data.memberships.map(m=>`<option value="${m.company_id}" ${m.company_id===data.activeCompany.id?'selected':''}>${esc(m.companies?.name||'Company')}</option>`).join('')}</select>`:''}<span class="beta">${esc(role)} · cloud beta</span><button class="btn secondary small" id="logout">Sign out</button></div></header><main class="wrap">${page(isManager)}</main><nav class="bottom-nav">${nav('home','⌂','Home')}${nav('jobs','▣','Jobs')}${nav('quotes','£','Quotes')}${nav('timesheets','◷','Time')}${nav('finance','◈','Finance')}${nav('team','♟','Team')}</nav><div class="toast" id="toast"></div></div>`;
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;render()});
  $('#logout').onclick=logout;$('#company')?.addEventListener('change',async e=>{companyId=e.target.value;await refresh()});bind(isManager)
}
function nav(v,i,t){return `<button class="nav ${view===v?'active':''}" data-nav="${v}"><b>${i}</b><span>${t}</span></button>`}
function page(m){return view==='jobs'?jobs(m):view==='quotes'?quotes(m):view==='timesheets'?timesheets():view==='finance'?finance(m):view==='team'?team(m):home(m)}

function home(m){
  const oq=data.quotes.filter(q=>q.status!=='accepted'),pipe=sum(oq.map(q=>num(q.total))),sheet=mySheet(),hrs=sum((sheet?.weekly_time_entries||[]).map(x=>num(x.hours))),pending=data.weeklyTimesheets.filter(x=>x.status==='submitted').length;
  const outstanding=sum((data.invoices||[]).map(invoiceOutstanding));
  const profit=sum((data.profitability||[]).map(x=>num(x.gross_profit)));
  return `<section class="hero"><div><p class="eyebrow">${esc(data.activeCompany.name)}</p><h2>Run the business, not the paperwork.</h2><p class="sub">Quotes → jobs → approved labour → profit → invoice → payment.</p></div>${m?'<button class="btn" data-go="quotes">+ New quote</button>':''}</section><div class="notice">Cloud mode is active. Company data is shared securely between manager and employee accounts.</div><section class="grid stats">${stat('Live jobs',data.jobs.length)}${stat('Quote pipeline',money.format(pipe))}${stat(m?'Outstanding':'My week',m?money.format(outstanding):`${hrsFmt(hrs)} hrs`)}${stat(m?'Gross profit':'Status',m?money.format(profit):(sheet?.status||'Draft'))}</section>${m?`<section class="card section"><div class="section-head"><div><h3>Money snapshot</h3><p>Based on approved labour and recorded job costs.</p></div><button class="btn secondary small" data-go="finance">Open finance</button></div>${financeMini()}</section>`:''}<section class="card section"><div class="section-head"><div><h3>Jobs</h3></div><button class="btn secondary small" data-go="jobs">View</button></div>${list(data.jobs.slice(0,5).map(jobCard))}</section>${m&&pending?`<section class="card section"><div class="section-head"><div><h3>${pending} timesheet${pending===1?'':'s'} waiting</h3></div><button class="btn small" data-go="team">Review</button></div></section>`:''}`
}
function financeMini(){const p=data.profitability||[];const revenue=sum(p.map(x=>num(x.agreed_value))),labour=sum(p.map(x=>num(x.labour_cost))),materials=sum(p.map(x=>num(x.material_cost))),gross=sum(p.map(x=>num(x.gross_profit)));return `<div class="grid stats finance-summary">${stat('Net revenue',money.format(revenue))}${stat('Labour cost',money.format(labour))}${stat('Materials',money.format(materials))}${stat('Gross profit',money.format(gross))}${stat('Outstanding',money.format(sum((data.invoices||[]).map(invoiceOutstanding))))}</div>`}

function jobs(m){return `<section class="hero"><div><p class="eyebrow">JOBS</p><h2>Jobs and team assignments.</h2><p class="sub">Employees can only book time to jobs they are assigned to.</p></div></section>${m?`<section class="card section"><div class="section-head"><h3>Add a job</h3></div><form id="jobform" class="form-grid"><div class="field"><label>Job title</label><input name="title" required></div><div class="field"><label>Address</label><input name="address"></div><div class="field"><label>Agreed net value (£)</label><input name="agreedValue" type="number" min="0" step=".01"></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div><button class="btn">Add job</button></form></section>`:''}<section class="card section"><div class="section-head"><div><h3>${data.jobs.length} jobs</h3><p>${m?'Assign team members from each card.':'Your company jobs.'}</p></div></div>${list(data.jobs.map(j=>jobManage(j,m)))}</section>`}
function jobCard(j){const p=profitFor(j.id);return `<div class="item"><div class="item-main"><strong>${esc(j.title)}</strong><small>${esc(customerName(j))} · ${esc(j.address||'No address')}</small>${p?`<small>Profit ${money.format(num(p.gross_profit))} · ${num(p.margin_percent).toFixed(1)}%</small>`:''}</div><span class="status">${esc(j.status)}</span></div>`}
function jobManage(j,m){const assigned=data.assignments.filter(a=>a.job_id===j.id).map(a=>data.members.find(x=>x.id===a.member_id)).filter(Boolean),p=profitFor(j.id);return `<div class="item"><div class="item-main"><strong>${esc(j.title)}</strong><small>${esc(j.address||'No address')}</small>${p&&m?`<small>Net value ${money.format(num(p.agreed_value))} · Actual profit ${money.format(num(p.gross_profit))}</small>`:''}${assigned.length?`<div class="assigns">${assigned.map(x=>`<span class="pill">${esc(x.full_name||x.role)}</span>`).join('')}</div>`:''}</div><div class="item-side"><span class="status">${esc(j.status)}</span>${m?`<div class="toolbar"><select data-assign-sel="${j.id}"><option value="">Assign…</option>${data.members.map(x=>`<option value="${x.id}">${esc(x.full_name||x.role)}</option>`).join('')}</select><button class="btn small" data-assign="${j.id}">Assign</button></div>`:''}</div></div>`}

function quotes(m){return `<section class="hero"><div><p class="eyebrow">QUOTES</p><h2>Interactive cloud quotes.</h2><p class="sub">Build the price, save it and turn it into a live job.</p></div></section>${m?`<div class="quote-layout"><section class="card section"><form id="quoteform" class="form-grid"><div class="field"><label>Customer</label><input name="customerName" required></div><div class="field"><label>Email</label><input name="customerEmail" type="email"></div><div class="field"><label>Phone</label><input name="customerPhone"></div><div class="field"><label>Address</label><input name="customerAddress"></div><div class="field full"><label>Job title</label><input name="quoteTitle" required></div><div class="field full"><label>Description</label><textarea name="quoteDescription"></textarea></div><div class="field"><label>Labour hours</label><input class="calc" name="labourHours" type="number" step=".25" min="0" value="6"></div><div class="field"><label>Hourly rate (£)</label><input class="calc" name="hourlyRate" type="number" step=".01" min="0" value="45"></div><div class="field"><label>Materials (£)</label><input class="calc" name="materialsCost" type="number" step=".01" min="0" value="320"></div><div class="field"><label>Callout (£)</label><input class="calc" name="calloutFee" type="number" step=".01" min="0" value="60"></div><div class="field"><label>VAT (%)</label><input class="calc" name="vatRate" type="number" min="0" value="20"></div><button class="btn">Save quote</button></form></section><aside class="card quote-total"><p class="eyebrow">LIVE TOTAL</p><div class="money-row"><span>Labour</span><strong id="qlab">£0.00</strong></div><div class="money-row"><span>Materials</span><strong id="qmat">£0.00</strong></div><div class="money-row"><span>Callout</span><strong id="qcall">£0.00</strong></div><div class="money-row"><span>Net subtotal</span><strong id="qsub">£0.00</strong></div><div class="money-row"><span>VAT</span><strong id="qvat">£0.00</strong></div><div class="money-row total"><span>Total</span><strong id="qtotal">£0.00</strong></div></aside></div>`:'<div class="notice">Employees can view quotes. Managers create and convert them.</div>'}<section class="card section" style="margin-top:14px"><div class="section-head"><h3>Saved quotes</h3></div>${list(data.quotes.map(q=>quoteCard(q,m)))}</section>`}
function quoteCard(q,m){return `<div class="item"><div class="item-main"><strong>${esc(q.title||q.description||'Quote')}</strong><small>${esc(q.customers?.name||'Customer')} · Labour ${hrsFmt(q.labour_hours)}h @ ${money.format(num(q.hourly_rate))}</small><small>Net ${money.format(num(q.subtotal))} + VAT ${money.format(num(q.vat))}</small></div><div class="item-side"><span class="amount">${money.format(num(q.total))}</span><span class="status ${q.status}">${esc(q.status)}</span>${m&&q.status!=='accepted'?`<button class="btn small" data-convert="${q.id}">Convert to job</button>`:''}</div></div>`}

function timesheets(){const s=mySheet(),locked=s&&['submitted','approved'].includes(s.status),entries=s?.weekly_time_entries||[],jobs=timeJobs(),days=weekDays(week),rows=jobs.map(j=>({j,h:days.map(d=>entries.find(e=>e.job_id===j.id&&e.work_date===iso(d))?.hours||0)})),dt=days.map((_,i)=>sum(rows.map(r=>num(r.h[i])))),total=sum(dt);return `<section class="hero"><div><p class="eyebrow">WEEKLY TIMESHEET</p><h2>Hours against specific jobs.</h2><p class="sub">Monday to Sunday. Approved hours feed actual job profit automatically.</p></div></section><section class="card section"><div class="weekbar"><div><strong>${esc(data.activeMembership.full_name||data.user.email)}</strong><div class="sub">${esc(s?.status||'Draft')}</div></div><div class="weeknav"><button class="btn secondary small" id="prev">‹</button><span class="weeklabel">${fmt.format(days[0])} – ${fmt.format(days[6])}</span><button class="btn secondary small" id="next">›</button></div></div>${jobs.length?`<div class="timesheet-wrap"><table><thead><tr><th class="job-col">Job</th>${days.map(d=>`<th>${day(d)}<br>${d.getDate()}</th>`).join('')}<th>Total</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="job-col"><strong>${esc(r.j.title)}</strong></td>${r.h.map((h,i)=>`<td><input class="hours" type="number" step=".25" min="0" max="24" value="${num(h)||''}" data-hour-job="${r.j.id}" data-hour-date="${iso(days[i])}" ${locked?'disabled':''}></td>`).join('')}<td class="row-total">${hrsFmt(sum(r.h.map(num)))}</td></tr>`).join('')}</tbody><tfoot><tr><td class="job-col">Daily total</td>${dt.map(x=>`<td>${hrsFmt(x)}</td>`).join('')}<td class="row-total">${hrsFmt(total)}</td></tr></tfoot></table></div>${locked?`<div class="actions"><span class="status ${s.status}">${esc(s.status)}</span></div>`:`<div class="actions"><button class="btn" id="submitweek" ${!s||total<=0?'disabled':''}>Submit week</button></div>`}`:empty('No jobs available. Ask a manager to assign you to a job.')}<section class="grid stats" style="margin-top:14px">${stat('Weekly hours',hrsFmt(total))}${stat('Jobs used',rows.filter(r=>sum(r.h.map(num))>0).length)}${stat('Status',s?.status||'Draft')}${stat('Week',week)}</section></section>`}

function finance(m){if(!m)return `<section class="hero"><div><p class="eyebrow">FINANCE</p><h2>Manager-only job finance.</h2><p class="sub">Your role can view operational records, but profit and payment controls are manager restricted.</p></div></section>`;
  const p=data.profitability||[],invoices=data.invoices||[];
  const revenue=sum(p.map(x=>num(x.agreed_value))),labour=sum(p.map(x=>num(x.labour_cost))),materials=sum(p.map(x=>num(x.material_cost))),expenses=sum(p.map(x=>num(x.expense_cost))),gross=sum(p.map(x=>num(x.gross_profit))),paid=sum(invoices.map(invoicePaid)),outstanding=sum(invoices.map(invoiceOutstanding));
  return `<section class="hero"><div><p class="eyebrow">JOB PROFIT & INVOICING</p><h2>Know what every job actually made.</h2><p class="sub">Approved labour, recorded materials and expenses update actual margin. Invoice and payment status sit beside it.</p></div></section><section class="grid stats finance-summary">${stat('Net job value',money.format(revenue))}${stat('Actual costs',money.format(labour+materials+expenses))}${stat('Gross profit',money.format(gross))}${stat('Paid',money.format(paid))}${stat('Outstanding',money.format(outstanding))}</section><section class="card section"><div class="section-head"><div><h3>Profit by job</h3><p>Net sales are compared with actual labour/material/expense cost.</p></div></div>${p.length?`<div class="finance-grid">${p.map(profitCard).join('')}</div>`:empty('Convert a quote to a job to start tracking profit.')}</section><section class="card section"><div class="section-head"><div><h3>Invoices & payments</h3><p>Create from a job, mark sent and record part or full payments.</p></div></div>${invoices.length?`<div class="list">${invoices.map(invoiceCard).join('')}</div>`:empty('No invoices yet. Create one from a job above.')}</section>`
}
function profitCard(p){const j=data.jobs.find(x=>x.id===p.job_id),inv=(data.invoices||[]).find(x=>x.job_id===p.job_id&&x.status!=='void'),cls=num(p.gross_profit)>=0?'profit-positive':'profit-negative';return `<div class="finance-card"><h4>${esc(j?.title||'Job')}</h4><p class="sub">${esc(customerName(j)||'No customer')}</p><div class="finance-metrics"><div class="metric"><small>Net value</small><strong>${money.format(num(p.agreed_value))}</strong></div><div class="metric"><small>Labour</small><strong>${money.format(num(p.labour_cost))}</strong></div><div class="metric"><small>Materials</small><strong>${money.format(num(p.material_cost))}</strong></div><div class="metric"><small>Expenses</small><strong>${money.format(num(p.expense_cost))}</strong></div><div class="metric"><small>Profit</small><strong class="${cls}">${money.format(num(p.gross_profit))}</strong></div><div class="metric"><small>Margin</small><strong class="${cls}">${num(p.margin_percent).toFixed(1)}%</strong></div><div class="metric"><small>Hours</small><strong>${hrsFmt(p.labour_hours)}h</strong></div><div class="metric"><small>Outstanding</small><strong>${money.format(num(p.outstanding_total))}</strong></div></div><div class="actions">${!inv&&num(p.agreed_value)>0?`<button class="btn small" data-create-invoice="${p.job_id}">Create invoice</button>`:inv?`<span class="status ${inv.status}">${esc(inv.status)}</span>`:''}</div><details class="details-form"><summary>+ Add material cost</summary><form data-material-form="${p.job_id}" class="mini-grid"><div class="field"><label>Description</label><input name="description" required placeholder="Cable, fittings…"></div><div class="field"><label>Qty</label><input name="quantity" type="number" min=".01" step=".01" value="1" required></div><div class="field"><label>Unit cost (£)</label><input name="unitCost" type="number" min="0" step=".01" required></div><button class="btn small">Add material</button></form></details></div>`}
function invoiceCard(i){const paid=invoicePaid(i),out=invoiceOutstanding(i),j=data.jobs.find(x=>x.id===i.job_id),overdue=i.status!=='paid'&&i.status!=='void'&&i.due_date&&new Date(i.due_date+'T23:59:59')<new Date();return `<div class="item invoice-card"><div class="item-main"><strong>${esc(i.invoice_number||'Invoice')} · ${esc(j?.title||'Job')}</strong><small>Due ${esc(i.due_date||'Not set')} · Net ${money.format(num(i.subtotal))} · VAT ${money.format(num(i.vat))}</small><small>Paid ${money.format(paid)} · Outstanding ${money.format(out)}</small>${(i.invoice_items||[]).map(x=>`<small>${esc(x.description)} · ${num(x.quantity)} × ${money.format(num(x.unit_price))}</small>`).join('')}</div><div class="item-side"><span class="amount">${money.format(num(i.total))}</span><span class="status ${overdue?'overdue':i.status}">${overdue?'overdue':esc(i.status)}</span><div class="actions">${i.status==='draft'?`<button class="btn small" data-invoice-status="${i.id}" data-status="sent">Mark sent</button>`:''}${overdue&&i.status!=='overdue'?`<button class="btn secondary small" data-invoice-status="${i.id}" data-status="overdue">Mark overdue</button>`:''}</div>${out>0&&i.status!=='void'?`<details class="details-form"><summary>Record payment</summary><form data-payment-form="${i.id}" class="mini-grid"><div class="field"><label>Amount (£)</label><input name="amount" type="number" min=".01" max="${out.toFixed(2)}" step=".01" value="${out.toFixed(2)}" required></div><div class="field"><label>Method</label><select name="method"><option>Bank transfer</option><option>Card</option><option>Cash</option><option>Other</option></select></div><div class="field"><label>Reference</label><input name="reference" placeholder="Optional"></div><button class="btn small">Save payment</button></form></details>`:''}</div></div>`}

function team(m){if(!m)return `<section class="hero"><div><p class="eyebrow">TEAM</p><h2>Your company team.</h2></div></section><section class="card section">${list(data.members.map(memberLine))}</section>`;const invite=['owner','admin'].includes(data.activeMembership.role),submitted=data.weeklyTimesheets.filter(x=>x.status==='submitted');return `<section class="hero"><div><p class="eyebrow">TEAM</p><h2>Invites and timesheet approvals.</h2><p class="sub">Approving a week locks its hourly employment cost into job profitability.</p></div></section><div class="team-grid"><section class="card section"><div class="section-head"><h3>Members</h3></div>${invite?`<form id="inviteform" class="form-grid" style="margin-bottom:14px"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Role</label><select name="role"><option value="employee">Employee</option><option value="manager">Manager</option>${data.activeMembership.role==='owner'?'<option value="admin">Admin</option>':''}</select></div><button class="btn">Create invite</button></form>`:''}<div class="list">${data.members.map(memberCard).join('')}</div></section><section class="card section"><div class="section-head"><h3>To review</h3></div>${submitted.length?`<div class="list">${submitted.map(reviewCard).join('')}</div>`:empty('Nothing waiting for approval.')}</section></div>`}
function memberLine(x){return `<div class="item"><div class="item-main"><strong>${esc(x.full_name||'Unnamed member')}</strong><small>${esc(x.role)}</small></div><span class="status">${esc(x.role)}</span></div>`}
function memberCard(x){const edit=['owner','admin'].includes(data.activeMembership.role)&&x.role!=='owner';return `<div class="item"><div class="item-main"><strong>${esc(x.full_name||'Unnamed member')}</strong><small>${esc(x.role)}</small></div><div class="item-side">${edit?`<div class="toolbar"><input class="cost-input" type="number" min="0" step=".01" value="${x.hourly_cost??''}" placeholder="£/hr" data-cost="${x.id}"><button class="btn small" data-save-cost="${x.id}">Save cost</button></div>`:`<span class="status">${esc(x.role)}</span>`}</div></div>`}
function reviewCard(s){const member=data.members.find(x=>x.user_id===s.user_id),hours=sum((s.weekly_time_entries||[]).map(x=>num(x.hours)));return `<div class="item"><div class="item-main"><strong>${esc(member?.full_name||'Team member')}</strong><small>Week ${esc(s.week_start)} · ${hrsFmt(hours)} hours · ${money.format(num(member?.hourly_cost))}/hr</small><input class="review-reason" data-review-reason="${s.id}" placeholder="Reason required only if rejecting"></div><div class="item-side"><button class="btn small" data-review="${s.id}" data-decision="approved">Approve</button><button class="btn danger small" data-review="${s.id}" data-decision="rejected">Reject</button></div></div>`}

function bind(m){
  document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{view=x.dataset.go;render()});
  $('#jobform')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await act('create_job',{companyId,title:f.get('title'),address:f.get('address'),notes:f.get('notes'),agreedValue:f.get('agreedValue')},'Job added')});
  document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=async()=>{const s=document.querySelector(`[data-assign-sel="${b.dataset.assign}"]`);if(!s?.value)return;await act('assign_job',{companyId,jobId:b.dataset.assign,memberId:s.value},'Job assigned')});
  const qf=$('#quoteform');if(qf){qf.querySelectorAll('.calc').forEach(x=>x.oninput=quoteCalc);qf.onsubmit=async e=>{e.preventDefault();await act('create_quote',{companyId,...Object.fromEntries(new FormData(qf).entries())},'Quote saved')};quoteCalc()}
  document.querySelectorAll('[data-convert]').forEach(b=>b.onclick=()=>act('convert_quote',{quoteId:b.dataset.convert},'Quote converted to job'));
  $('#prev')?.addEventListener('click',async()=>{week=addDays(week,-7);await refresh()});$('#next')?.addEventListener('click',async()=>{week=addDays(week,7);await refresh()});
  document.querySelectorAll('[data-hour-job]').forEach(i=>i.onchange=async()=>{await act('upsert_time',{companyId,weekStart:week,jobId:i.dataset.hourJob,workDate:i.dataset.hourDate,hours:i.value},'Hours saved',false)});
  $('#submitweek')?.addEventListener('click',()=>{const s=mySheet();if(s)act('submit_week',{weeklyTimesheetId:s.id},'Week submitted')});
  $('#inviteform')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await act('invite',{companyId,email:f.get('email'),role:f.get('role')},'Invitation created')});
  document.querySelectorAll('[data-save-cost]').forEach(b=>b.onclick=()=>{const i=document.querySelector(`[data-cost="${b.dataset.saveCost}"]`);act('update_member_cost',{companyId,memberId:b.dataset.saveCost,hourlyCost:i?.value??''},'Hourly cost saved')});
  document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const s=data.weeklyTimesheets.find(x=>x.id===b.dataset.review),mem=data.members.find(x=>x.user_id===s?.user_id),reason=document.querySelector(`[data-review-reason="${b.dataset.review}"]`)?.value||'';if(b.dataset.decision==='rejected'&&!reason.trim()){toast('Add a rejection reason');return}act('review_week',{weeklyTimesheetId:b.dataset.review,decision:b.dataset.decision,hourlyCost:mem?.hourly_cost??0,reason},`Week ${b.dataset.decision}`)});
  document.querySelectorAll('[data-material-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);await act('add_material',{companyId,jobId:f.dataset.materialForm,description:fd.get('description'),quantity:fd.get('quantity'),unitCost:fd.get('unitCost')},'Material added')});
  document.querySelectorAll('[data-create-invoice]').forEach(b=>b.onclick=()=>act('create_invoice',{jobId:b.dataset.createInvoice},'Invoice created'));
  document.querySelectorAll('[data-invoice-status]').forEach(b=>b.onclick=()=>act('invoice_status',{invoiceId:b.dataset.invoiceStatus,status:b.dataset.status},`Invoice marked ${b.dataset.status}`));
  document.querySelectorAll('[data-payment-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);await act('record_payment',{invoiceId:f.dataset.paymentForm,amount:fd.get('amount'),method:fd.get('method'),reference:fd.get('reference')},'Payment recorded')});
}

async function act(api,body,message,reload=true){try{await req(api,body);if(message)toast(message);if(reload)await refresh()}catch(e){toast(e.message==='AUTH'?'Please sign in again':e.message,true)}}
async function logout(){try{await req('signout',{})}catch{}companyId=null;data=null;auth()}
function quoteCalc(){const f=$('#quoteform');if(!f)return;const x=new FormData(f),h=num(x.get('labourHours')),r=num(x.get('hourlyRate')),mat=num(x.get('materialsCost')),call=num(x.get('calloutFee')),vr=num(x.get('vatRate')),lab=h*r,sub=lab+mat+call,vat=sub*vr/100,total=sub+vat;set('#qlab',money.format(lab));set('#qmat',money.format(mat));set('#qcall',money.format(call));set('#qsub',money.format(sub));set('#qvat',money.format(vat));set('#qtotal',money.format(total))}

function mySheet(){return data.weeklyTimesheets.find(x=>x.user_id===data.user.id&&x.week_start===week)||null}
function timeJobs(){if(data.activeMembership.role!=='employee')return data.jobs;const ids=new Set(data.assignments.filter(a=>a.member_id===data.activeMembership.id).map(a=>a.job_id));return data.jobs.filter(j=>ids.has(j.id))}
function profitFor(jobId){return (data.profitability||[]).find(x=>x.job_id===jobId)}
function invoicePaid(i){return sum((i.payments||[]).map(x=>num(x.amount)))}
function invoiceOutstanding(i){return Math.max(0,num(i.total)-invoicePaid(i))}
function customerName(j){return j?.customers?.name||''}
function list(items){return items.length?`<div class="list">${items.join('')}</div>`:empty('Nothing here yet.')}
function stat(a,b){return `<div class="card stat"><span>${esc(a)}</span><strong>${esc(String(b))}</strong></div>`}
function empty(t){return `<div class="empty">${esc(t)}</div>`}
function toast(t,bad=false){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.toggle('bad',bad);x.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>x.classList.remove('show'),2200)}
function $(s){return document.querySelector(s)}function set(s,t){const x=$(s);if(x)x.textContent=t}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}function sum(a){return a.reduce((x,y)=>x+num(y),0)}function hrsFmt(v){const n=Math.round(num(v)*100)/100;return Number.isInteger(n)?String(n):n.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}
function monday(d){const x=new Date(d);x.setHours(12,0,0,0);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);return iso(x)}function parseIso(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)}function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function addDays(s,n){const d=parseIso(s);d.setDate(d.getDate()+n);return iso(d)}function weekDays(s){const d=parseIso(s);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return x})}function day(d){return ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d.getDay()]}
})();
