(()=>{
  const SUPABASE_URL='https://nynssdxfmjfqgodgynnu.supabase.co',KEY='sb_publishable_ose18MeKd0ZPfTM1tbq2fg_hzfVcTxf';
  const sb=window.supabase.createClient(SUPABASE_URL,KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),root=document.querySelector('#doc'),money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});
  const token=new URLSearchParams(location.search).get('t');let current=null;if(!token){fail('This quote link is missing.');return}load();
  async function load(){try{let r=await sb.rpc('get_public_quote_v2',{share_token:token});if(r.error)r=await sb.rpc('get_public_quote',{share_token:token});if(r.error)throw r.error;current=r.data;render(current)}catch(e){fail(e?.message||'Could not load this quote.')}}
  function render(q){
    const rawStatus=String(q.status||'draft').toLowerCase(),expired=isExpired(q.valid_until)&&!['accepted','rejected'].includes(rawStatus),status=expired?'expired':rawStatus,canReply=!['accepted','rejected','expired'].includes(status),items=Array.isArray(q.items)?q.items:[];
    const brand=document.querySelector('.doc-brand strong'),sub=document.querySelector('.doc-brand small');if(brand)brand.textContent=q.company_name||'Veystead';if(sub)sub.textContent=q.trade_type||'Customer quote';
    const business=[q.company_address,q.company_phone,q.company_email,q.company_website].filter(Boolean).map(esc).join('\n'),registrations=[q.company_number?`Company no. ${esc(q.company_number)}`:'',q.vat_number?`VAT no. ${esc(q.vat_number)}`:''].filter(Boolean).join(' · '),totals=calcTotals(q,items.filter(x=>!x.optional||x.selected).map(x=>x.id));
    root.innerHTML=`<article class="doc-paper"><header class="doc-head"><p class="doc-kicker">QUOTE</p><h1>${esc(q.title||'Quotation')}</h1><div class="doc-head-sub"><span class="doc-ref">${esc(q.quote_number||'Quote')} · ${date(q.created_at)}${q.valid_until?` · Valid until ${dateOnly(q.valid_until)}`:''}</span><span class="doc-status ${esc(status)}">${esc(status.replace('_',' '))}</span></div></header><div class="doc-body"><div class="doc-grid"><div class="doc-info"><span>From</span><strong>${esc(q.company_name||'Trade business')}${q.trade_type?`\n${esc(q.trade_type)}`:''}${business?`\n${business}`:''}</strong>${registrations?`<small class="doc-mini">${registrations}</small>`:''}</div><div class="doc-info"><span>Prepared for</span><strong>${esc(q.customer_name||'Customer')}${q.customer_address?`\n${esc(q.customer_address)}`:''}</strong></div></div>${q.description?`<section class="doc-section"><h2>Work included</h2><p class="doc-copy">${esc(q.description)}</p></section>`:''}${items.length?itemsMarkup(items,status,canReply):legacyBreakdown(q)}${items.length?`<section class="doc-section"><h2>Price</h2><div class="doc-breakdown"><div class="doc-row"><span>Net</span><strong data-live-net>${money.format(totals.net)}</strong></div>${Number(q.discount_percent||0)>0?`<div class="doc-row doc-discount"><span>Discount</span><strong>${Number(q.discount_percent)}%</strong></div>`:''}<div class="doc-row"><span>VAT</span><strong data-live-vat>${money.format(totals.vat)}</strong></div><div class="doc-row total"><span>Total</span><strong data-live-total>${money.format(totals.total)}</strong></div></div>${canReply&&items.some(x=>x.optional)?'<p class="doc-live-note">The total updates as you choose optional extras.</p>':''}</section>`:''}${q.quote_terms?`<section class="doc-section doc-terms"><h2>Terms</h2><p class="doc-copy">${esc(q.quote_terms)}</p></section>`:''}${status==='accepted'?result('Quote accepted',`Accepted${q.accepted_at?` on ${date(q.accepted_at)}`:''}. The job is now in the trade business workflow.`):status==='rejected'?result('Quote declined',`Response recorded${q.rejected_at?` on ${date(q.rejected_at)}`:''}.`):status==='expired'?`<div class="doc-result expired"><strong>Quote expired</strong><p>Please contact ${esc(q.company_name||'the trade business')} for an updated quotation.</p></div>`:canReply?`<div class="doc-actions"><button class="doc-btn decline" data-answer="rejected">Decline</button><button class="doc-btn primary" data-answer="accepted">Accept quote</button></div><p class="doc-note">By accepting, you confirm you want ${esc(q.company_name||'the trade business')} to proceed with the quoted work and any optional extras you selected, subject to the terms above.</p>`:''}<div class="doc-actions single"><button class="doc-btn" data-print>Print / Save PDF</button></div></div></article>`;
    root.querySelectorAll('[data-option-id]').forEach(x=>x.addEventListener('change',()=>updateLiveTotals(q)));root.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>respond(b.dataset.answer,b)));root.querySelector('[data-print]')?.addEventListener('click',()=>window.print());
  }
  function itemsMarkup(items,status,canReply){const base=items.filter(x=>!x.optional),optional=items.filter(x=>x.optional);return `<section class="doc-section"><h2>Quote items</h2><div class="doc-item-list">${base.map(itemLine).join('')}</div></section>${optional.length?`<section class="doc-section"><h2>Optional extras</h2>${optional.map(i=>optionLine(i,status,canReply)).join('')}</section>`:''}`;}
  function itemLine(i){return `<div class="doc-item"><div class="doc-item-main"><strong>${esc(i.description)}</strong><small>${num(i.quantity)} × ${money.format(num(i.unit_price))} · VAT ${num(i.vat_rate)}%</small></div><span class="doc-item-price">${money.format(num(i.line_total))}</span></div>`;}
  function optionLine(i,status,canReply){const included=!!i.selected;if(canReply)return `<label class="doc-option"><input type="checkbox" data-option-id="${esc(i.id)}"><span class="doc-option-copy"><strong>${esc(i.description)} <span class="doc-badge">OPTIONAL</span></strong><small>${num(i.quantity)} × ${money.format(num(i.unit_price))} · VAT ${num(i.vat_rate)}%</small></span><span class="doc-option-price">+${money.format(num(i.line_total))}</span></label>`;return `<div class="doc-option"><span class="doc-option-copy"><strong>${esc(i.description)} <span class="doc-badge ${included?'included':'not-included'}">${included?'INCLUDED':'NOT INCLUDED'}</span></strong><small>${num(i.quantity)} × ${money.format(num(i.unit_price))} · VAT ${num(i.vat_rate)}%</small></span><span class="doc-option-price">${money.format(num(i.line_total))}</span></div>`;}
  function legacyBreakdown(q){const labour=Number(q.labour_hours||0)*Number(q.hourly_rate||0);return `<section class="doc-section"><h2>Price</h2><div class="doc-breakdown"><div class="doc-row"><span>Labour</span><strong>${money.format(labour)}</strong></div><div class="doc-row"><span>Materials</span><strong>${money.format(Number(q.materials_cost||0))}</strong></div>${Number(q.callout_fee||0)?`<div class="doc-row"><span>Call-out</span><strong>${money.format(Number(q.callout_fee))}</strong></div>`:''}<div class="doc-row"><span>Net</span><strong>${money.format(Number(q.subtotal||0))}</strong></div><div class="doc-row"><span>VAT</span><strong>${money.format(Number(q.vat||0))}</strong></div><div class="doc-row total"><span>Total</span><strong>${money.format(Number(q.total||0))}</strong></div></div></section>`;}
  function selectedOptionIds(){return [...root.querySelectorAll('[data-option-id]:checked')].map(x=>x.dataset.optionId);}function updateLiveTotals(q){const totals=calcTotals(q,selectedOptionIds()),a=root.querySelector('[data-live-net]'),b=root.querySelector('[data-live-vat]'),c=root.querySelector('[data-live-total]');if(a)a.textContent=money.format(totals.net);if(b)b.textContent=money.format(totals.vat);if(c)c.textContent=money.format(totals.total);}
  function calcTotals(q,selectedIds=[]){const items=Array.isArray(q.items)?q.items:[];if(!items.length)return{net:num(q.subtotal),vat:num(q.vat),total:num(q.total)};const selected=new Set(selectedIds),factor=1-Math.max(0,Math.min(100,num(q.discount_percent)))/100;let net=0,vat=0;for(const i of items){if(i.optional&&!selected.has(i.id))continue;net+=num(i.line_subtotal)*factor;vat+=num(i.line_vat)*factor;}net=round2(net);vat=round2(vat);return{net,vat,total:round2(net+vat)};}
  async function respond(answer,btn){const buttons=[...root.querySelectorAll('[data-answer]')];buttons.forEach(x=>x.disabled=true);const old=btn.textContent;btn.textContent=answer==='accepted'?'Accepting…':'Declining…';try{let r=await sb.rpc('respond_public_quote_v2',{share_token:token,response:answer,selected_optional_items:answer==='accepted'?selectedOptionIds():[]});if(r.error&&!(current?.items||[]).length)r=await sb.rpc('respond_public_quote',{share_token:token,response:answer});if(r.error)throw r.error;await load()}catch(e){buttons.forEach(x=>x.disabled=false);btn.textContent=old;const msg=document.createElement('div');msg.className='doc-result error';msg.innerHTML=`<strong>Could not save your response</strong><p>${esc(e?.message||'Please try again.')}</p>`;root.querySelector('.doc-body')?.appendChild(msg)}}
  function result(title,text){return `<div class="doc-result"><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`}function fail(m){root.innerHTML=`<div class="doc-error"><strong>Quote unavailable</strong><div>${esc(m)}</div></div>`}function isExpired(v){if(!v)return false;const d=new Date(`${v}T23:59:59`);return !Number.isNaN(d.getTime())&&d.getTime()<Date.now()}function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(d)}function dateOnly(v){const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(d)}function num(v){const x=Number(v);return Number.isFinite(x)?x:0}function round2(v){return Math.round((v+Number.EPSILON)*100)/100}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();
