(()=>{
  const SUPABASE_URL='https://nynssdxfmjfqgodgynnu.supabase.co',KEY='sb_publishable_ose18MeKd0ZPfTM1tbq2fg_hzfVcTxf';
  const sb=window.supabase.createClient(SUPABASE_URL,KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),root=document.querySelector('#doc'),money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});
  const token=new URLSearchParams(location.search).get('t');if(!token){fail('This quote link is missing.');return}load();
  async function load(){try{const r=await sb.rpc('get_public_quote',{share_token:token});if(r.error)throw r.error;render(r.data)}catch(e){fail(e?.message||'Could not load this quote.')}}
  function render(q){
    const rawStatus=String(q.status||'draft').toLowerCase(),expired=isExpired(q.valid_until)&&!['accepted','rejected'].includes(rawStatus),status=expired?'expired':rawStatus,labour=Number(q.labour_hours||0)*Number(q.hourly_rate||0),canReply=!['accepted','rejected','expired'].includes(status);
    const brand=document.querySelector('.doc-brand strong'),sub=document.querySelector('.doc-brand small');if(brand)brand.textContent=q.company_name||'TradeOS';if(sub)sub.textContent=q.trade_type||'Customer quote';
    const business=[q.company_address,q.company_phone,q.company_email,q.company_website].filter(Boolean).map(esc).join('\n');
    const registrations=[q.company_number?`Company no. ${esc(q.company_number)}`:'',q.vat_number?`VAT no. ${esc(q.vat_number)}`:''].filter(Boolean).join(' · ');
    root.innerHTML=`<article class="doc-paper"><header class="doc-head"><p class="doc-kicker">QUOTE</p><h1>${esc(q.title||'Quotation')}</h1><div class="doc-head-sub"><span class="doc-ref">${esc(q.quote_number||'Quote')} · ${date(q.created_at)}${q.valid_until?` · Valid until ${dateOnly(q.valid_until)}`:''}</span><span class="doc-status ${esc(status)}">${esc(status.replace('_',' '))}</span></div></header><div class="doc-body">
      <div class="doc-grid"><div class="doc-info"><span>From</span><strong>${esc(q.company_name||'Trade business')}${q.trade_type?`\n${esc(q.trade_type)}`:''}${business?`\n${business}`:''}</strong>${registrations?`<small class="doc-mini">${registrations}</small>`:''}</div><div class="doc-info"><span>Prepared for</span><strong>${esc(q.customer_name||'Customer')}${q.customer_address?`\n${esc(q.customer_address)}`:''}</strong></div></div>
      ${q.description?`<section class="doc-section"><h2>Work included</h2><p class="doc-copy">${esc(q.description)}</p></section>`:''}
      <section class="doc-section"><h2>Price</h2><div class="doc-breakdown"><div class="doc-row"><span>Labour</span><strong>${money.format(labour)}</strong></div><div class="doc-row"><span>Materials</span><strong>${money.format(Number(q.materials_cost||0))}</strong></div>${Number(q.callout_fee||0)?`<div class="doc-row"><span>Call-out</span><strong>${money.format(Number(q.callout_fee))}</strong></div>`:''}<div class="doc-row"><span>Net</span><strong>${money.format(Number(q.subtotal||0))}</strong></div><div class="doc-row"><span>VAT</span><strong>${money.format(Number(q.vat||0))}</strong></div><div class="doc-row total"><span>Total</span><strong>${money.format(Number(q.total||0))}</strong></div></div></section>
      ${q.quote_terms?`<section class="doc-section doc-terms"><h2>Terms</h2><p class="doc-copy">${esc(q.quote_terms)}</p></section>`:''}
      ${status==='accepted'?result('Quote accepted',`Accepted${q.accepted_at?` on ${date(q.accepted_at)}`:''}. The job is now in the trade business workflow.`):status==='rejected'?result('Quote declined',`Response recorded${q.rejected_at?` on ${date(q.rejected_at)}`:''}.`):status==='expired'?`<div class="doc-result expired"><strong>Quote expired</strong><p>Please contact ${esc(q.company_name||'the trade business')} for an updated quotation.</p></div>`:canReply?`<div class="doc-actions"><button class="doc-btn decline" data-answer="rejected">Decline</button><button class="doc-btn primary" data-answer="accepted">Accept quote</button></div><p class="doc-note">By accepting, you confirm you want ${esc(q.company_name||'the trade business')} to proceed with the quoted work subject to the terms above.</p>`:''}
      <div class="doc-actions single"><button class="doc-btn" data-print>Print / Save PDF</button></div>
    </div></article>`;
    root.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>respond(b.dataset.answer,b)));root.querySelector('[data-print]')?.addEventListener('click',()=>window.print());
  }
  async function respond(answer,btn){const buttons=[...root.querySelectorAll('[data-answer]')];buttons.forEach(x=>x.disabled=true);const old=btn.textContent;btn.textContent=answer==='accepted'?'Accepting…':'Declining…';try{const r=await sb.rpc('respond_public_quote',{share_token:token,response:answer});if(r.error)throw r.error;await load()}catch(e){buttons.forEach(x=>x.disabled=false);btn.textContent=old;const msg=document.createElement('div');msg.className='doc-result error';msg.innerHTML=`<strong>Could not save your response</strong><p>${esc(e?.message||'Please try again.')}</p>`;root.querySelector('.doc-body')?.appendChild(msg)}}
  function result(title,text){return `<div class="doc-result"><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`}
  function fail(m){root.innerHTML=`<div class="doc-error"><strong>Quote unavailable</strong><div>${esc(m)}</div></div>`}
  function isExpired(v){if(!v)return false;const d=new Date(`${v}T23:59:59`);return !Number.isNaN(d.getTime())&&d.getTime()<Date.now()}
  function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(d)}
  function dateOnly(v){const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(d)}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();